x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER:-maybe_user}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-maybe_password}
  POSTGRES_DB: ${POSTGRES_DB:-maybe_production}

x-rails-env: &rails_env
  <<: *db_env
  SECRET_KEY_BASE: ${SECRET_KEY_BASE:-a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3c3bc86d86b6b0b307df30d9a6a90a2066a3fa9e67c5e6f374dbd7dd4e0778e13}
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  RAILS_ENV: "production"
  DB_HOST: db
  DB_PORT: 5432
  REDIS_URL: redis://redis:6379/1
  DOCKER_CONTAINER: "true"
  BIND: "tcp://0.0.0.0:3000"
  BUILD_COMMIT_SHA: ${BUILD_COMMIT_SHA:-self-hosted}
  # Alpha Vantage API key for crypto prices (free tier: 25 requests/day)
  ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
  # Finnhub REST provider for stocks/crypto prices (free tier: 25 requests/minute)
  FINNHUB_API_KEY: ${FINNHUB_API_KEY}
  # Provider selection (defaults keep Finnhub for stocks/crypto)
  PRICE_PROVIDER_STOCKS: ${PRICE_PROVIDER_STOCKS:-finnhub}
  PRICE_PROVIDER_CRYPTO: ${PRICE_PROVIDER_CRYPTO:-finnhub}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_COMMIT_SHA: ${BUILD_COMMIT_SHA:-self-hosted}
    volumes:
      - app-storage:/rails/storage
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      <<: *rails_env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - maybe_net
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_COMMIT_SHA: ${BUILD_COMMIT_SHA:-self-hosted}
    command: bundle exec sidekiq
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      <<: *rails_env
    networks:
      - maybe_net

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - maybe_net

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - maybe_net

volumes:
  app-storage:
  postgres-data:
  redis-data:

networks:
  maybe_net:
    driver: bridge
